### ISSUE TITLE
Currently does not work on latest CEF_VERSION and breaks using RelWithDebInfo

### ISSUE THREAD

**Issue by rjindael** [iboB/cef-cmake#4]
There are critical issues that don't allow you to use the library properly:
- attempts copying old files that don't exist in newer CEF versions (fatal error)
- does not properly work with RelWithDebInfo (tries accessing nonexistent "RelWithDebInfo" folder instead of "Release") (fatal error)
- incorrectly copies files to a different directory on MSVC (annoying)

I've fixed all these issues in my pull request #3.

**Comment by iboB** [comment]
Closed by #3
